[2025-06-08 17:51:09,378: INFO: main: This is an info message from the Kidney Disease Classification module.]
[2025-06-08 18:09:17,141: INFO: main: This is an info message from the Kidney Disease Classification module.]
[2025-06-08 18:16:22,284: INFO: main: This is an info message from the Kidney Disease Classification module.]
[2025-06-21 10:37:51,950: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-21 10:37:51,964: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-21 10:37:51,978: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-21 10:37:51,979: INFO: common: created directory at: artifacts]
[2025-06-21 10:37:51,979: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-21 10:37:51,979: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-21 10:41:08,670: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-21 10:41:51,667: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-23 11:09:50,803: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 11:16:34,543: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 11:16:34,578: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 11:17:47,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 11:17:47,538: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 11:17:47,543: INFO: common: created directory at: artifacts]
[2025-06-23 11:17:47,545: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-23 11:19:34,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 11:19:35,002: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 11:19:35,004: INFO: common: created directory at: artifacts]
[2025-06-23 11:19:35,006: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-23 11:21:15,443: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 11:21:15,448: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 11:21:15,450: INFO: common: created directory at: artifacts]
[2025-06-23 11:21:15,452: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-23 11:23:31,714: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 11:23:31,718: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 11:23:31,720: INFO: common: created directory at: artifacts]
[2025-06-23 11:23:31,722: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-23 11:23:32,218: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-23 12:39:24,463: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-23 12:39:24,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 12:39:24,474: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 12:39:24,475: INFO: common: created directory at: artifacts]
[2025-06-23 12:39:24,476: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-23 12:39:24,476: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-23 12:45:13,239: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-23 12:45:32,892: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-23 12:45:32,893: INFO: main: *******************]
[2025-06-23 12:45:32,894: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-23 12:45:32,897: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 12:45:32,899: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 12:45:32,900: INFO: common: created directory at: artifacts]
[2025-06-23 12:45:32,901: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-23 12:45:32,901: ERROR: main: get_base_model() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    prepare_base_model.main()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\pipeline\stage_02_prepare_base_model.py", line 16, in main
    PrepareBaseModel.get_base_model()
TypeError: get_base_model() missing 1 required positional argument: 'self'
[2025-06-23 12:49:05,789: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-23 12:49:05,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 12:49:05,794: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 12:49:05,795: INFO: common: created directory at: artifacts]
[2025-06-23 12:49:05,796: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-23 12:49:05,796: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-23 12:56:18,745: ERROR: main: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))]
Traceback (most recent call last):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 748, in _error_catcher
    yield
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 873, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 856, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\socket.py", line 681, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 949, in read
    data = self._raw_read(amt)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 902, in _raw_read
    self._fp.close()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 775, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    obj.main()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\components\data_ingestion.py", line 33, in download_file
    raise e
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[2025-06-23 13:14:18,537: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-23 13:14:18,537: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:14:18,546: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 13:14:18,546: INFO: common: created directory at: artifacts]
[2025-06-23 13:14:18,546: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-23 13:14:18,546: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-23 13:18:42,262: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-23 13:19:09,094: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-23 13:19:09,094: INFO: main: *******************]
[2025-06-23 13:19:09,094: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-23 13:19:09,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:19:09,094: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 13:19:09,094: INFO: common: created directory at: artifacts]
[2025-06-23 13:19:09,103: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-23 13:19:10,228: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-23 13:19:12,119: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-23 13:34:44,664: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:34:44,677: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 13:34:44,677: INFO: common: created directory at: artifacts]
[2025-06-23 13:43:46,238: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:43:46,248: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 13:43:46,256: INFO: common: created directory at: artifacts]
[2025-06-23 13:45:01,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:45:01,320: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 13:45:01,323: INFO: common: created directory at: artifacts]
[2025-06-23 13:45:26,706: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:45:26,708: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 13:45:26,716: INFO: common: created directory at: artifacts]
[2025-06-23 13:45:26,725: INFO: common: created directory at: artifacts\training]
[2025-06-23 13:47:36,147: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:49:30,797: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:49:30,809: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 13:49:30,813: INFO: common: created directory at: artifacts]
[2025-06-23 13:49:30,817: INFO: common: created directory at: artifacts\training]
[2025-06-23 13:51:14,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 13:51:14,627: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 13:51:14,632: INFO: common: created directory at: artifacts]
[2025-06-23 13:51:14,637: INFO: common: created directory at: artifacts\training]
[2025-06-23 14:01:53,833: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 14:01:53,850: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 14:01:53,859: INFO: common: created directory at: artifacts]
[2025-06-23 14:01:53,867: INFO: common: created directory at: artifacts\training]
[2025-06-23 14:03:53,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 14:03:53,665: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 14:03:53,668: INFO: common: created directory at: artifacts]
[2025-06-23 14:03:53,672: INFO: common: created directory at: artifacts\training]
[2025-06-23 14:04:58,903: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 14:04:58,910: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 14:04:58,915: INFO: common: created directory at: artifacts]
[2025-06-23 14:04:58,918: INFO: common: created directory at: artifacts\training]
[2025-06-23 14:06:31,429: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 14:06:31,436: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 14:06:31,439: INFO: common: created directory at: artifacts]
[2025-06-23 14:06:31,442: INFO: common: created directory at: artifacts\training]
[2025-06-23 14:12:23,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 14:12:23,357: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 14:12:23,367: INFO: common: created directory at: artifacts]
[2025-06-23 14:12:23,378: INFO: common: created directory at: artifacts\training]
[2025-06-23 14:15:37,286: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 14:15:37,294: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 14:15:37,298: INFO: common: created directory at: artifacts]
[2025-06-23 14:15:37,302: INFO: common: created directory at: artifacts\training]
[2025-06-23 14:33:23,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 14:33:23,262: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 14:33:23,269: INFO: common: created directory at: artifacts]
[2025-06-23 14:33:23,278: INFO: common: created directory at: artifacts\training]
[2025-06-23 15:41:40,364: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 15:41:40,379: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 15:41:40,387: INFO: common: created directory at: artifacts]
[2025-06-23 15:41:40,400: INFO: common: created directory at: artifacts\training]
[2025-06-23 16:24:40,722: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 16:24:40,755: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 16:24:40,768: INFO: common: created directory at: artifacts]
[2025-06-23 16:24:40,793: INFO: common: created directory at: artifacts\training]
[2025-06-23 16:41:51,432: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 16:41:51,462: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 16:41:51,481: INFO: common: created directory at: artifacts]
[2025-06-23 16:41:51,532: INFO: common: created directory at: artifacts\training]
[2025-06-23 17:01:39,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 17:01:39,476: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 17:01:39,476: INFO: common: created directory at: artifacts]
[2025-06-23 17:01:39,476: INFO: common: created directory at: artifacts\training]
[2025-06-23 17:05:35,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 17:05:35,312: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 17:05:35,316: INFO: common: created directory at: artifacts]
[2025-06-23 17:05:35,317: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-23 17:05:36,056: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-23 17:05:41,187: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 17:05:41,203: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 17:05:41,211: INFO: common: created directory at: artifacts]
[2025-06-23 17:05:41,218: INFO: common: created directory at: artifacts\training]
[2025-06-23 17:26:19,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 17:26:19,548: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 17:26:19,553: INFO: common: created directory at: artifacts]
[2025-06-23 17:26:19,557: INFO: common: created directory at: artifacts\training]
[2025-06-23 18:09:46,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 18:09:46,631: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 18:09:46,635: INFO: common: created directory at: artifacts]
[2025-06-23 18:09:46,638: INFO: common: created directory at: artifacts\training]
[2025-06-23 22:04:22,167: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 22:04:22,180: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 22:04:22,189: INFO: common: created directory at: artifacts]
[2025-06-23 22:05:45,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 22:05:45,558: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 22:05:45,560: INFO: common: created directory at: artifacts]
[2025-06-23 22:05:49,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 22:05:49,833: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 22:05:49,835: INFO: common: created directory at: artifacts]
[2025-06-23 22:07:33,517: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 22:07:33,522: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 22:07:33,525: INFO: common: created directory at: artifacts]
[2025-06-23 22:32:06,224: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 22:32:06,264: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 22:32:06,278: INFO: common: created directory at: artifacts]
[2025-06-23 22:33:28,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 22:33:28,956: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 22:33:28,958: INFO: common: created directory at: artifacts]
[2025-06-23 22:40:09,750: INFO: common: json file saved at: scores.json]
[2025-06-23 22:51:36,234: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 22:51:36,248: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 22:51:36,257: INFO: common: created directory at: artifacts]
[2025-06-23 22:58:04,767: INFO: common: json file saved at: scores.json]
[2025-06-23 23:02:58,485: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 23:02:58,493: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 23:02:58,510: INFO: common: created directory at: artifacts]
[2025-06-23 23:09:33,640: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 23:09:33,644: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 23:09:33,644: INFO: common: created directory at: artifacts]
[2025-06-23 23:15:48,621: INFO: common: json file saved at: scores.json]
[2025-06-23 23:24:23,621: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 23:24:23,629: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 23:24:23,635: INFO: common: created directory at: artifacts]
[2025-06-23 23:29:29,697: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 23:29:29,701: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 23:29:29,701: INFO: common: created directory at: artifacts]
[2025-06-23 23:35:54,998: INFO: common: json file saved at: scores.json]
[2025-06-23 23:39:49,894: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-23 23:39:49,911: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-23 23:39:49,919: INFO: common: created directory at: artifacts]
[2025-06-23 23:48:10,661: INFO: common: json file saved at: scores.json]
[2025-06-24 00:26:50,922: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 00:26:50,944: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 00:26:50,953: INFO: common: created directory at: artifacts]
[2025-06-24 00:35:19,492: INFO: common: json file saved at: scores.json]
[2025-06-24 00:40:13,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 00:40:13,682: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 00:40:13,688: INFO: common: created directory at: artifacts]
[2025-06-24 00:47:18,940: INFO: common: json file saved at: scores.json]
[2025-06-24 01:12:06,455: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 01:12:06,462: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 01:12:06,464: INFO: common: created directory at: artifacts]
[2025-06-24 01:18:27,209: INFO: common: json file saved at: scores.json]
[2025-06-24 01:26:46,544: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 01:26:46,560: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 01:26:46,568: INFO: common: created directory at: artifacts]
[2025-06-24 01:33:01,372: INFO: common: json file saved at: scores.json]
[2025-06-24 01:38:48,039: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 01:38:48,053: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 01:38:48,061: INFO: common: created directory at: artifacts]
[2025-06-24 01:44:57,765: INFO: common: json file saved at: scores.json]
[2025-06-24 01:47:30,770: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 01:47:30,775: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 01:47:30,776: INFO: common: created directory at: artifacts]
[2025-06-24 01:48:39,762: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 01:48:39,766: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 01:48:39,766: INFO: common: created directory at: artifacts]
[2025-06-24 01:54:45,618: INFO: common: json file saved at: scores.json]
[2025-06-24 01:57:37,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 01:57:37,840: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 01:57:37,840: INFO: common: created directory at: artifacts]
[2025-06-24 02:04:04,841: INFO: common: json file saved at: scores.json]
[2025-06-24 02:10:09,313: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 02:10:09,322: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 02:10:09,322: INFO: common: created directory at: artifacts]
[2025-06-24 02:17:59,637: INFO: common: json file saved at: scores.json]
[2025-06-24 02:18:04,554: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-06-24 02:18:06,407: INFO: builder_impl: Assets written to: C:\Users\CHIRAG~1\AppData\Local\Temp\tmprgpzuyt3\model\data\model\assets]
[2025-06-24 10:29:51,027: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-24 10:29:51,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 10:29:51,059: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 10:29:51,062: INFO: common: created directory at: artifacts]
[2025-06-24 10:29:51,062: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 10:29:51,064: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 10:32:15,989: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 10:32:35,588: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-24 10:32:35,591: INFO: main: *******************]
[2025-06-24 10:32:35,591: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-24 10:32:35,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 10:32:35,647: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 10:32:35,660: INFO: common: created directory at: artifacts]
[2025-06-24 10:32:35,668: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-24 10:32:36,863: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-24 10:32:37,951: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-24 10:32:37,951: INFO: main: *******************]
[2025-06-24 10:32:37,951: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-24 10:32:37,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 10:32:37,957: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 10:32:37,958: INFO: common: created directory at: artifacts]
[2025-06-24 10:32:37,959: INFO: common: created directory at: artifacts\training]
[2025-06-24 10:32:37,977: ERROR: main: name 'Training' is not defined]
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    model_trainer.main()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\pipeline\stage_03_training_model.py", line 17, in main
    training = Training(config=training_config)
NameError: name 'Training' is not defined
[2025-06-24 10:41:11,717: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-24 10:41:11,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 10:41:11,765: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 10:41:11,765: INFO: common: created directory at: artifacts]
[2025-06-24 10:41:11,765: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 10:41:11,765: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 10:43:53,061: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 10:44:24,713: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-24 10:44:24,713: INFO: main: *******************]
[2025-06-24 10:44:24,713: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-24 10:44:24,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 10:44:24,721: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 10:44:24,721: INFO: common: created directory at: artifacts]
[2025-06-24 10:44:24,721: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-24 10:44:26,196: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-24 10:44:31,949: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-24 10:44:31,949: INFO: main: *******************]
[2025-06-24 10:44:31,949: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-24 10:44:31,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 10:44:31,954: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 10:44:31,954: INFO: common: created directory at: artifacts]
[2025-06-24 10:44:31,954: INFO: common: created directory at: artifacts\training]
[2025-06-24 10:44:31,954: ERROR: main: name 'Training' is not defined]
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    model_trainer.main()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\pipeline\stage_03_training_model.py", line 17, in main
    training = Training(config=training_config)
NameError: name 'Training' is not defined
[2025-06-24 11:06:46,657: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-24 11:06:46,661: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 11:06:46,665: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 11:06:46,667: INFO: common: created directory at: artifacts]
[2025-06-24 11:06:46,667: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 11:06:46,668: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 11:09:36,553: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 11:09:58,237: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-24 11:09:58,238: INFO: main: *******************]
[2025-06-24 11:09:58,238: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-24 11:09:58,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 11:09:58,249: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 11:09:58,252: INFO: common: created directory at: artifacts]
[2025-06-24 11:09:58,254: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-24 11:09:59,839: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-24 11:10:05,838: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-24 11:10:05,838: INFO: main: *******************]
[2025-06-24 11:10:05,839: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-24 11:10:05,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 11:10:05,849: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 11:10:05,850: INFO: common: created directory at: artifacts]
[2025-06-24 11:10:05,851: INFO: common: created directory at: artifacts\training]
[2025-06-24 21:32:41,899: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-24 21:32:41,910: INFO: main: *******************]
[2025-06-24 21:32:41,910: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-24 21:32:41,934: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 21:32:41,943: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 21:32:41,949: INFO: common: created directory at: artifacts]
[2025-06-24 21:32:41,953: ERROR: main: name 'Evaluation' is not defined]
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    model_evalution.main()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\pipeline\stage_04_model_evaluation.py", line 17, in main
    evaluation = Evaluation(eval_config)
NameError: name 'Evaluation' is not defined
[2025-06-24 22:17:52,300: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-24 22:17:52,305: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 22:17:52,308: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 22:17:52,309: INFO: common: created directory at: artifacts]
[2025-06-24 22:17:52,309: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 22:17:52,310: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 22:18:49,191: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-24 22:18:49,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 22:18:49,198: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 22:18:49,198: INFO: common: created directory at: artifacts]
[2025-06-24 22:18:49,199: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 22:18:49,200: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 22:27:22,237: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-24 22:27:22,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 22:27:22,245: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 22:27:22,247: INFO: common: created directory at: artifacts]
[2025-06-24 22:27:22,247: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 22:27:22,248: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 22:37:33,661: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 22:37:57,725: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-24 22:53:37,777: INFO: stage_02_prepare_base_model: *******************]
[2025-06-24 22:53:37,777: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-24 22:53:37,777: ERROR: stage_02_prepare_base_model: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py", line 28, in <module>
    obj = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2025-06-24 23:01:06,003: INFO: stage_02_prepare_base_model: *******************]
[2025-06-24 23:01:06,004: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-24 23:01:06,005: ERROR: stage_02_prepare_base_model: name 'config' is not defined]
Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py", line 29, in <module>
    obj = PrepareBaseModel(config=config)
NameError: name 'config' is not defined
[2025-06-24 23:05:52,585: INFO: stage_02_prepare_base_model: *******************]
[2025-06-24 23:05:52,586: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-24 23:05:52,641: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 23:05:52,646: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 23:05:52,648: INFO: common: created directory at: artifacts]
[2025-06-24 23:05:52,649: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-24 23:05:53,611: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-24 23:05:54,018: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2025-06-24 23:10:41,627: INFO: stage_03_model_training: *******************]
[2025-06-24 23:10:41,628: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-24 23:10:41,631: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 23:10:41,635: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 23:10:41,636: INFO: common: created directory at: artifacts]
[2025-06-24 23:10:41,637: INFO: common: created directory at: artifacts\training]
[2025-06-24 23:32:13,786: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-24 23:41:52,292: INFO: stage_04_model_evaluation: *******************]
[2025-06-24 23:41:52,293: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-24 23:41:52,297: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 23:41:52,302: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 23:41:52,304: INFO: common: created directory at: artifacts]
[2025-06-24 23:41:53,547: ERROR: stage_04_model_evaluation: name 'model' is not defined]
Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_04_model_evaluation.py", line 31, in <module>
    obj.main()
  File "src/Kidney_Disease_Classification/pipeline/stage_04_model_evaluation.py", line 19, in main
    evaluation.evaluation()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\components\model_evaluation.py", line 48, in evaluation
    self.score = model.evaluate(self.valid_generator)
NameError: name 'model' is not defined
[2025-06-24 23:49:57,763: INFO: stage_04_model_evaluation: *******************]
[2025-06-24 23:49:57,764: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-24 23:49:57,767: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 23:49:57,772: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 23:49:57,772: INFO: common: created directory at: artifacts]
[2025-06-24 23:58:03,728: INFO: common: json file saved at: scores.json]
[2025-06-24 23:58:03,731: INFO: common: json file saved at: scores.json]
[2025-06-24 23:58:03,732: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-25 07:43:17,289: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 07:43:17,297: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 07:44:14,398: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 07:44:14] "GET / HTTP/1.1" 200 -]
[2025-06-25 07:44:50,934: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-06-25 07:44:50,943: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 07:44:50] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 07:46:12,017: INFO: _internal: 10.167.200.185 - - [25/Jun/2025 07:46:12] "GET / HTTP/1.1" 200 -]
[2025-06-25 07:47:10,189: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-06-25 07:47:10,189: INFO: _internal: 10.167.200.185 - - [25/Jun/2025 07:47:10] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 07:50:33,461: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 07:50:33,461: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 07:50:45,671: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 07:50:45] "GET / HTTP/1.1" 200 -]
[2025-06-25 07:50:56,064: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-06-25 07:50:56,077: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 07:50:56] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 08:21:50,246: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 08:21:50,248: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 08:24:29,013: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 08:24:29,015: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 08:24:48,465: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:24:48] "GET / HTTP/1.1" 200 -]
[2025-06-25 08:25:02,398: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:25:02] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 08:27:58,698: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 08:27:58,698: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 08:28:16,355: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:28:16] "GET / HTTP/1.1" 200 -]
[2025-06-25 08:28:27,551: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:28:27] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 08:30:28,893: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 08:30:28,893: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 08:30:28,899: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:30:48,521: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 08:30:48,521: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 08:30:48,531: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:30:55,089: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:30:55,106: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:31:08,466: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:31:08] "GET / HTTP/1.1" 200 -]
[2025-06-25 08:31:16,351: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:31:16] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 08:31:33,310: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\app.py', reloading]
[2025-06-25 08:31:34,094: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:31:41,153: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:31:41,166: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:32:47,355: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\app.py', reloading]
[2025-06-25 08:32:48,108: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:32:54,654: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:32:54,664: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:37:33,005: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\utils\\common.py', reloading]
[2025-06-25 08:37:34,258: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:37:43,938: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:37:43,946: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:37:46,028: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\utils\\common.py', reloading]
[2025-06-25 08:37:46,740: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:37:53,215: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:37:53,223: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:38:15,428: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 08:38:15,428: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 08:38:15,428: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:38:22,344: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:38:22,353: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:38:53,770: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:38:53] "GET / HTTP/1.1" 200 -]
[2025-06-25 08:39:03,286: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:39:03] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 08:41:24,922: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\app.py', reloading]
[2025-06-25 08:41:25,727: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:41:34,533: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:41:34,543: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:42:34,091: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 08:42:34,091: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 08:42:34,096: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:42:40,770: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:42:40,787: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:42:48,334: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:42:48] "GET / HTTP/1.1" 200 -]
[2025-06-25 08:42:57,729: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 08:42:57] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 08:47:25,539: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\move_model.py', reloading]
[2025-06-25 08:47:27,989: INFO: _internal:  * Restarting with stat]
[2025-06-25 08:47:40,070: WARNING: _internal:  * Debugger is active!]
[2025-06-25 08:47:40,084: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 08:54:04,207: INFO: stage_02_prepare_base_model: *******************]
[2025-06-25 08:54:04,207: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-25 08:54:04,216: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 08:54:04,216: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 08:54:04,216: INFO: common: created directory at: artifacts]
[2025-06-25 08:54:04,224: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 08:54:05,023: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 08:54:05,356: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2025-06-25 08:54:20,729: INFO: stage_03_model_training: *******************]
[2025-06-25 08:54:20,729: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 08:54:20,739: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 08:54:20,742: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 08:54:20,742: INFO: common: created directory at: artifacts]
[2025-06-25 08:54:20,744: INFO: common: created directory at: artifacts\training]
[2025-06-25 08:59:27,546: INFO: stage_02_prepare_base_model: *******************]
[2025-06-25 08:59:27,546: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-25 08:59:27,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 08:59:27,555: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 08:59:27,555: INFO: common: created directory at: artifacts]
[2025-06-25 08:59:27,555: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 08:59:28,096: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 08:59:28,438: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2025-06-25 08:59:43,639: INFO: stage_03_model_training: *******************]
[2025-06-25 08:59:43,639: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 08:59:43,640: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 08:59:43,640: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 08:59:43,640: INFO: common: created directory at: artifacts]
[2025-06-25 08:59:43,640: INFO: common: created directory at: artifacts\training]
[2025-06-25 09:47:44,541: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-25 09:48:32,613: INFO: stage_04_model_evaluation: *******************]
[2025-06-25 09:48:32,614: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-25 09:48:32,619: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 09:48:32,623: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 09:48:32,624: INFO: common: created directory at: artifacts]
[2025-06-25 10:13:48,375: INFO: common: json file saved at: scores.json]
[2025-06-25 10:13:48,531: INFO: common: json file saved at: scores.json]
[2025-06-25 10:13:48,543: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-25 10:15:03,830: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 10:15:03,831: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 10:15:03,834: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:15:11,739: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:15:11,752: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:15:19,079: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:15:19] "GET / HTTP/1.1" 200 -]
[2025-06-25 10:15:28,752: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:15:28] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 10:18:26,945: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\pipeline\\prediction.py', reloading]
[2025-06-25 10:18:27,927: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:19:16,807: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 10:19:16,808: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 10:19:16,811: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:19:23,601: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:19:23,617: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:19:39,963: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:19:39] "GET / HTTP/1.1" 200 -]
[2025-06-25 10:19:49,187: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-06-25 10:19:49,901: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:19:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 10:23:00,317: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\pipeline\\prediction.py', reloading]
[2025-06-25 10:23:01,213: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:23:19,071: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 10:23:19,071: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 10:23:19,074: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:23:25,056: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:23:25,075: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:24:05,669: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:24:05] "GET / HTTP/1.1" 200 -]
[2025-06-25 10:24:17,131: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-06-25 10:24:17,887: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:24:17] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 10:26:00,089: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\pipeline\\prediction.py', reloading]
[2025-06-25 10:26:00,821: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:26:07,573: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:26:07,580: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:26:37,287: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 10:26:37,288: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 10:26:37,290: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:26:43,373: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:26:43,379: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:26:53,903: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:26:53] "GET / HTTP/1.1" 200 -]
[2025-06-25 10:27:04,014: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-06-25 10:27:04,535: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:27:04] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 10:28:00,258: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\pipeline\\prediction.py', reloading]
[2025-06-25 10:28:01,151: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:28:10,045: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:28:10,052: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:28:30,924: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 10:28:30,924: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 10:28:30,927: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:28:36,723: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:28:36,729: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:28:51,576: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:28:51] "GET / HTTP/1.1" 200 -]
[2025-06-25 10:29:01,751: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-06-25 10:29:02,293: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:29:02] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 10:31:13,650: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\pipeline\\prediction.py', reloading]
[2025-06-25 10:31:14,326: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:31:21,174: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:31:21,181: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:31:44,913: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 10:31:44,913: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 10:31:44,915: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:31:51,681: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:31:51,690: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:32:04,095: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:32:04] "GET / HTTP/1.1" 200 -]
[2025-06-25 10:32:13,078: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-06-25 10:32:13,831: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:32:13] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 10:32:32,843: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-06-25 10:32:33,199: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:32:33] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 10:33:12,849: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-06-25 10:33:13,202: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:33:13] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 10:33:38,921: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-06-25 10:33:39,448: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 10:33:39] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 10:45:38,536: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\components\\prepare_base_model.py', reloading]
[2025-06-25 10:45:42,148: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:45:54,387: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:45:54,397: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:50:51,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 10:50:51,958: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 10:50:51,962: INFO: common: created directory at: artifacts]
[2025-06-25 10:50:51,964: INFO: common: created directory at: prediction_model]
[2025-06-25 10:50:57,726: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 10:52:06,307: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 10:52:06,310: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 10:52:06,312: INFO: common: created directory at: artifacts]
[2025-06-25 10:52:06,314: INFO: common: created directory at: artifacts\training]
[2025-06-25 10:54:32,196: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\components\\model_training.py', reloading]
[2025-06-25 10:55:09,991: INFO: _internal:  * Restarting with stat]
[2025-06-25 10:57:53,357: WARNING: _internal:  * Debugger is active!]
[2025-06-25 10:57:53,560: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 10:58:18,541: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 10:58:18,548: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 10:58:18,553: INFO: common: created directory at: artifacts]
[2025-06-25 10:58:18,556: INFO: common: created directory at: artifacts\training]
[2025-06-25 11:01:30,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:01:30,192: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:01:30,201: INFO: common: created directory at: artifacts]
[2025-06-25 11:01:30,206: INFO: common: created directory at: prediction_model]
[2025-06-25 11:01:31,450: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 11:02:01,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:02:01,498: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:02:01,503: INFO: common: created directory at: artifacts]
[2025-06-25 11:02:01,514: INFO: common: created directory at: artifacts\training]
[2025-06-25 11:04:52,185: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:04:52,190: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:04:52,192: INFO: common: created directory at: artifacts]
[2025-06-25 11:04:52,194: INFO: common: created directory at: prediction_model]
[2025-06-25 11:04:52,848: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 11:05:02,189: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:05:02,200: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:05:02,204: INFO: common: created directory at: artifacts]
[2025-06-25 11:05:02,211: INFO: common: created directory at: artifacts\training]
[2025-06-25 11:27:43,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:27:43,829: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:27:43,839: INFO: common: created directory at: artifacts]
[2025-06-25 11:27:43,848: INFO: common: created directory at: artifacts\training]
[2025-06-25 11:33:03,829: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\components\\prepare_base_model.py', reloading]
[2025-06-25 11:33:08,562: INFO: _internal:  * Restarting with stat]
[2025-06-25 11:33:40,703: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-25 11:33:40,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:33:40,892: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:33:40,896: INFO: common: created directory at: artifacts]
[2025-06-25 11:33:40,907: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-25 11:33:40,907: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-25 11:38:11,590: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-25 11:38:30,355: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-25 11:43:19,869: INFO: stage_02_prepare_base_model: *******************]
[2025-06-25 11:43:19,869: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-25 11:43:19,877: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:43:19,885: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:43:19,887: INFO: common: created directory at: artifacts]
[2025-06-25 11:43:19,887: INFO: common: created directory at: prediction_model]
[2025-06-25 11:43:20,650: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 11:43:21,339: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2025-06-25 11:43:39,240: INFO: stage_03_model_training: *******************]
[2025-06-25 11:43:39,240: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 11:43:39,240: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:43:39,240: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:43:39,240: INFO: common: created directory at: artifacts]
[2025-06-25 11:43:39,240: INFO: common: created directory at: artifacts\training]
[2025-06-25 11:43:39,760: ERROR: stage_03_model_training: unsupported operand type(s) for ** or pow(): 'str' and 'dict']
Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_03_model_training.py", line 30, in <module>
    obj.main()
  File "src/Kidney_Disease_Classification/pipeline/stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\components\model_training.py", line 41, in train_valid_generator
    class_mode = "binary" # Assuming binary classification
TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'dict'
[2025-06-25 11:48:30,008: INFO: stage_03_model_training: *******************]
[2025-06-25 11:48:30,008: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 11:48:30,011: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 11:48:30,014: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 11:48:30,014: INFO: common: created directory at: artifacts]
[2025-06-25 11:48:30,014: INFO: common: created directory at: artifacts\training]
[2025-06-25 11:48:30,783: ERROR: stage_03_model_training: unsupported operand type(s) for ** or pow(): 'str' and 'dict']
Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_03_model_training.py", line 30, in <module>
    obj.main()
  File "src/Kidney_Disease_Classification/pipeline/stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\components\model_training.py", line 41, in train_valid_generator
    class_mode = "binary" # Assuming binary classification
TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'dict'
[2025-06-25 12:00:05,130: INFO: stage_03_model_training: *******************]
[2025-06-25 12:00:05,130: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 12:00:05,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 12:00:05,138: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 12:00:05,138: INFO: common: created directory at: artifacts]
[2025-06-25 12:00:05,138: INFO: common: created directory at: artifacts\training]
[2025-06-25 12:22:24,884: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-25 12:41:46,731: INFO: stage_03_model_training: *******************]
[2025-06-25 12:41:46,731: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 12:41:46,750: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 12:41:46,754: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 12:41:46,756: INFO: common: created directory at: artifacts]
[2025-06-25 12:41:46,756: INFO: common: created directory at: artifacts\training]
[2025-06-25 13:17:48,789: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-25 13:25:05,355: INFO: stage_03_model_training: *******************]
[2025-06-25 13:25:05,355: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 13:25:05,361: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:25:05,366: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:25:05,367: INFO: common: created directory at: artifacts]
[2025-06-25 13:25:05,367: INFO: common: created directory at: artifacts\training]
[2025-06-25 15:10:56,122: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-25 15:20:39,257: INFO: stage_02_prepare_base_model: *******************]
[2025-06-25 15:20:39,258: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-25 15:20:39,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 15:20:39,266: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 15:20:39,268: INFO: common: created directory at: artifacts]
[2025-06-25 15:20:39,268: INFO: common: created directory at: prediction_model]
[2025-06-25 15:20:40,200: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 15:20:41,063: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2025-06-25 15:20:53,393: INFO: stage_03_model_training: *******************]
[2025-06-25 15:20:53,394: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 15:20:53,397: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 15:20:53,399: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 15:20:53,400: INFO: common: created directory at: artifacts]
[2025-06-25 15:20:53,400: INFO: common: created directory at: artifacts\training]
[2025-06-25 15:54:23,476: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-25 15:56:15,654: INFO: stage_02_prepare_base_model: *******************]
[2025-06-25 15:56:15,655: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-25 15:56:15,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 15:56:15,662: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 15:56:15,662: INFO: common: created directory at: artifacts]
[2025-06-25 15:56:15,663: INFO: common: created directory at: prediction_model]
[2025-06-25 15:56:16,236: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 15:56:16,513: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2025-06-25 15:56:28,418: INFO: stage_03_model_training: *******************]
[2025-06-25 15:56:28,418: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 15:56:28,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 15:56:28,423: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 15:56:28,424: INFO: common: created directory at: artifacts]
[2025-06-25 15:56:28,425: INFO: common: created directory at: artifacts\training]
[2025-06-25 16:21:41,405: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-25 16:27:46,847: INFO: stage_03_model_training: *******************]
[2025-06-25 16:27:46,847: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 16:27:46,851: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 16:27:46,855: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 16:27:46,856: INFO: common: created directory at: artifacts]
[2025-06-25 16:27:46,857: INFO: common: created directory at: artifacts\training]
[2025-06-25 16:54:06,705: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-25 16:54:50,736: INFO: stage_04_model_evaluation: *******************]
[2025-06-25 16:54:50,736: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-25 16:54:50,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 16:54:50,745: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 16:54:50,746: INFO: common: created directory at: artifacts]
[2025-06-25 17:01:49,128: INFO: common: json file saved at: scores.json]
[2025-06-25 17:01:49,137: INFO: common: json file saved at: scores.json]
[2025-06-25 17:01:49,140: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-25 17:08:58,165: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 17:08:58,166: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 17:08:58,171: INFO: _internal:  * Restarting with stat]
[2025-06-25 17:09:04,795: WARNING: _internal:  * Debugger is active!]
[2025-06-25 17:09:04,807: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 17:09:39,047: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:09:39] "GET / HTTP/1.1" 200 -]
[2025-06-25 17:10:06,322: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:10:06] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-25 17:18:02,974: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\move_model.py', reloading]
[2025-06-25 17:18:04,850: INFO: _internal:  * Restarting with stat]
[2025-06-25 17:18:49,835: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 17:18:49,835: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 17:18:49,838: INFO: _internal:  * Restarting with stat]
[2025-06-25 17:18:56,481: WARNING: _internal:  * Debugger is active!]
[2025-06-25 17:18:56,491: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 17:19:01,110: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:19:01] "GET / HTTP/1.1" 200 -]
[2025-06-25 17:19:11,145: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:19:11] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 17:19:23,537: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:19:23] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 17:19:44,386: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:19:44] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 17:25:32,125: INFO: _internal:  * Detected change in 'C:\\Users\\Chirag Sharma\\Desktop\\gitdemo\\Kidney-Disease-Classification\\src\\Kidney_Disease_Classification\\pipeline\\prediction.py', reloading]
[2025-06-25 17:25:33,591: INFO: _internal:  * Restarting with stat]
[2025-06-25 17:28:57,355: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.167.200.185:8080]
[2025-06-25 17:28:57,356: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-25 17:28:57,360: INFO: _internal:  * Restarting with stat]
[2025-06-25 17:29:04,909: WARNING: _internal:  * Debugger is active!]
[2025-06-25 17:29:04,921: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-06-25 17:29:27,706: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:29:27] "GET / HTTP/1.1" 200 -]
[2025-06-25 17:29:47,338: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:29:47] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 17:30:33,645: INFO: _internal: 127.0.0.1 - - [25/Jun/2025 17:30:33] "POST /predict HTTP/1.1" 200 -]
[2025-06-25 17:41:20,461: INFO: stage_03_model_training: *******************]
[2025-06-25 17:41:20,462: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 17:41:20,466: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 17:41:20,471: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 17:41:20,474: INFO: common: created directory at: artifacts]
[2025-06-25 17:41:20,475: INFO: common: created directory at: artifacts\training]
[2025-06-25 17:45:10,134: INFO: stage_02_prepare_base_model: *******************]
[2025-06-25 17:45:10,134: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-25 17:45:10,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 17:45:10,141: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 17:45:10,143: INFO: common: created directory at: artifacts]
[2025-06-25 17:45:10,143: INFO: common: created directory at: prediction_model]
[2025-06-25 17:45:10,854: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 17:45:11,008: ERROR: stage_02_prepare_base_model: Cannot convert '1e-4' to EagerTensor of dtype float]
Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py", line 30, in <module>
    pipeline.main()
  File "src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py", line 21, in main
    base_model.update_base_model()
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\components\prepare_base_model.py", line 53, in update_base_model
    self.full_model = self._prepare_full_model(
  File "C:\Users\Chirag Sharma\Desktop\gitdemo\Kidney-Disease-Classification\src\Kidney_Disease_Classification\components\prepare_base_model.py", line 44, in _prepare_full_model
    optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate),
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\optimizers\sgd.py", line 123, in __init__
    self._learning_rate = self._build_learning_rate(learning_rate)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\optimizers\optimizer.py", line 394, in _build_learning_rate
    return tf.Variable(
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\tensorflow\python\framework\constant_op.py", line 103, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
TypeError: Cannot convert '1e-4' to EagerTensor of dtype float
[2025-06-25 17:46:25,276: INFO: stage_02_prepare_base_model: *******************]
[2025-06-25 17:46:25,276: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-06-25 17:46:25,279: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 17:46:25,281: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 17:46:25,282: INFO: common: created directory at: artifacts]
[2025-06-25 17:46:25,282: INFO: common: created directory at: prediction_model]
[2025-06-25 17:46:25,741: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-25 17:46:26,036: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2025-06-25 17:46:40,104: INFO: stage_03_model_training: *******************]
[2025-06-25 17:46:40,105: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 17:46:40,108: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 17:46:40,110: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 17:46:40,111: INFO: common: created directory at: artifacts]
[2025-06-25 17:46:40,112: INFO: common: created directory at: artifacts\training]
[2025-06-25 18:05:28,293: INFO: stage_03_model_training: *******************]
[2025-06-25 18:05:28,294: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-25 18:05:28,297: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 18:05:28,301: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 18:05:28,301: INFO: common: created directory at: artifacts]
[2025-06-25 18:05:28,302: INFO: common: created directory at: artifacts\training]
[2025-06-30 11:33:20,269: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 11:33:20,274: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 11:33:20,276: INFO: common: created directory at: artifacts]
[2025-06-30 11:33:20,277: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 11:33:20,279: INFO: 328411276: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-30 11:38:22,085: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 11:38:22,103: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 11:38:22,110: INFO: common: created directory at: artifacts]
[2025-06-30 11:38:22,114: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 11:38:22,117: INFO: 328411276: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-30 11:45:34,970: INFO: 328411276: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-30 11:46:07,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 11:46:07,917: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 11:46:07,919: INFO: common: created directory at: artifacts]
[2025-06-30 11:46:07,920: INFO: common: created directory at: artifacts\training]
[2025-06-30 11:48:51,886: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 11:48:51,894: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 11:48:51,897: INFO: common: created directory at: artifacts]
[2025-06-30 11:48:51,900: INFO: common: created directory at: prediction_model]
[2025-06-30 11:48:52,575: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-30 11:48:58,130: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 11:48:58,133: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 11:48:58,135: INFO: common: created directory at: artifacts]
[2025-06-30 11:48:58,136: INFO: common: created directory at: prediction_model]
[2025-06-30 11:48:58,593: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-30 12:29:03,440: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 12:29:03,466: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 12:29:03,474: INFO: common: created directory at: artifacts]
[2025-06-30 12:29:03,477: INFO: common: created directory at: prediction_model]
[2025-06-30 12:29:04,530: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-30 12:29:45,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 12:29:45,612: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 12:29:45,617: INFO: common: created directory at: artifacts]
[2025-06-30 12:29:45,624: INFO: common: created directory at: artifacts\training]
[2025-06-30 15:50:48,778: INFO: stage_03_model_training: *******************]
[2025-06-30 15:50:48,779: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-30 15:50:48,806: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 15:50:48,811: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 15:50:48,812: INFO: common: created directory at: artifacts]
[2025-06-30 15:50:48,813: INFO: common: created directory at: artifacts\training]
[2025-06-30 19:56:19,415: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-30 20:14:55,921: INFO: stage_03_model_training: *******************]
[2025-06-30 20:14:55,921: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-30 20:14:55,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 20:14:55,937: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 20:14:55,937: INFO: common: created directory at: artifacts]
[2025-06-30 20:14:55,937: INFO: common: created directory at: artifacts\training]
[2025-06-30 23:26:49,875: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-30 23:27:24,387: INFO: stage_04_model_evaluation: *******************]
[2025-06-30 23:27:24,387: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-30 23:27:24,405: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 23:27:24,405: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 23:27:24,409: INFO: common: created directory at: artifacts]
[2025-06-30 23:34:16,807: INFO: common: json file saved at: scores.json]
[2025-06-30 23:34:16,810: INFO: common: json file saved at: scores.json]
[2025-06-30 23:34:16,812: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-01 10:54:18,183: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.69.98.185:8080]
[2025-07-01 10:54:18,185: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-01 10:54:18,185: INFO: _internal:  * Restarting with stat]
[2025-07-01 10:54:25,461: WARNING: _internal:  * Debugger is active!]
[2025-07-01 10:54:25,475: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-07-01 10:54:42,009: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 10:54:42] "GET / HTTP/1.1" 200 -]
[2025-07-01 10:55:13,931: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 10:55:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-07-01 10:58:04,814: INFO: _internal:  * Detected change in 'c:\\users\\chirag sharma\\desktop\\gitdemo\\kidney-disease-classification\\src\\Kidney_Disease_Classification\\pipeline\\prediction.py', reloading]
[2025-07-01 10:58:06,272: INFO: _internal:  * Restarting with stat]
[2025-07-01 10:58:16,238: WARNING: _internal:  * Debugger is active!]
[2025-07-01 10:58:16,251: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-07-01 10:58:38,824: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.69.98.185:8080]
[2025-07-01 10:58:38,824: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-01 10:58:38,829: INFO: _internal:  * Restarting with stat]
[2025-07-01 10:58:45,660: WARNING: _internal:  * Debugger is active!]
[2025-07-01 10:58:45,660: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-07-01 10:59:02,791: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 10:59:02] "GET / HTTP/1.1" 200 -]
[2025-07-01 10:59:15,091: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 10:59:15] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 11:01:12,298: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 11:01:12] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 11:01:25,281: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 11:01:25] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 11:01:39,365: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 11:01:39] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 18:13:08,017: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:13:08,033: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:13:08,034: INFO: common: created directory at: artifacts]
[2025-07-01 18:13:08,036: INFO: common: created directory at: prediction_model]
[2025-07-01 18:13:09,009: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:16:00,977: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:16:00,984: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:16:00,988: INFO: common: created directory at: artifacts]
[2025-07-01 18:16:00,992: INFO: common: created directory at: prediction_model]
[2025-07-01 18:16:01,836: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:19:50,531: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:19:50,538: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:19:50,541: INFO: common: created directory at: artifacts]
[2025-07-01 18:19:50,544: INFO: common: created directory at: prediction_model]
[2025-07-01 18:19:51,198: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:20:23,941: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.69.98.185:8080]
[2025-07-01 18:20:23,941: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-01 18:20:23,946: INFO: _internal:  * Restarting with stat]
[2025-07-01 18:20:32,246: WARNING: _internal:  * Debugger is active!]
[2025-07-01 18:20:32,259: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-07-01 18:20:42,702: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 18:20:42] "GET / HTTP/1.1" 200 -]
[2025-07-01 18:21:00,738: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 18:21:00] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 18:35:08,509: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:35:08,570: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:35:08,577: INFO: common: created directory at: artifacts]
[2025-07-01 18:35:08,582: INFO: common: created directory at: artifacts]
[2025-07-01 18:35:09,801: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:36:13,569: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:36:13,575: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:36:13,579: INFO: common: created directory at: artifacts]
[2025-07-01 18:36:13,581: INFO: common: created directory at: artifacts]
[2025-07-01 18:36:14,388: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:38:53,053: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:38:53,059: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:38:53,061: INFO: common: created directory at: artifacts]
[2025-07-01 18:38:53,063: INFO: common: created directory at: artifacts]
[2025-07-01 18:38:53,753: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:41:33,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:41:33,317: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:41:33,323: INFO: common: created directory at: artifacts]
[2025-07-01 18:41:33,327: INFO: common: created directory at: artifacts]
[2025-07-01 18:41:34,220: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:42:13,006: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:42:13,010: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:42:13,012: INFO: common: created directory at: artifacts]
[2025-07-01 18:42:13,020: INFO: common: created directory at: artifacts]
[2025-07-01 18:42:13,602: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:48:14,705: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:48:14,726: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:48:14,732: INFO: common: created directory at: artifacts]
[2025-07-01 18:48:14,738: INFO: common: created directory at: artifacts]
[2025-07-01 18:48:15,641: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:51:36,475: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:51:36,479: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:51:36,481: INFO: common: created directory at: artifacts]
[2025-07-01 18:51:36,484: INFO: common: created directory at: artifacts]
[2025-07-01 18:51:37,066: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:51:59,312: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:51:59,318: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:51:59,321: INFO: common: created directory at: artifacts]
[2025-07-01 18:51:59,324: INFO: common: created directory at: artifacts]
[2025-07-01 18:51:59,943: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:56:05,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:56:05,600: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:56:05,613: INFO: common: created directory at: artifacts]
[2025-07-01 18:56:05,619: INFO: common: created directory at: artifacts]
[2025-07-01 18:56:06,713: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 18:56:33,058: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-01 18:56:33,063: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:56:33,066: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 18:56:33,067: INFO: common: created directory at: artifacts]
[2025-07-01 18:56:33,068: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-01 18:56:33,069: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-01 19:04:51,411: ERROR: stage_01_data_ingestion: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))]
Traceback (most recent call last):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\socket.py", line 681, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 593, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\urllib3\response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "src/Kidney_Disease_Classification/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\users\chirag sharma\desktop\gitdemo\kidney-disease-classification\src\Kidney_Disease_Classification\components\data_ingestion.py", line 33, in download_file
    raise e
  File "c:\users\chirag sharma\desktop\gitdemo\kidney-disease-classification\src\Kidney_Disease_Classification\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
[2025-07-01 19:26:12,444: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-01 19:26:12,448: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:26:12,452: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 19:26:12,453: INFO: common: created directory at: artifacts]
[2025-07-01 19:26:12,454: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-01 19:26:12,455: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-01 19:46:01,985: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11-1L5Ee7Ot-oDBnJY-B6CDwgnM8rFC6e/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-07-01 19:46:31,559: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-01 19:51:04,914: INFO: stage_02_prepare_base_model: *******************]
[2025-07-01 19:51:04,915: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-07-01 19:51:04,920: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:51:04,924: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 19:51:04,926: INFO: common: created directory at: artifacts]
[2025-07-01 19:51:04,926: INFO: common: created directory at: artifacts]
[2025-07-01 19:51:05,671: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 19:51:06,962: ERROR: stage_02_prepare_base_model: Unknown optimizer: 'tf.keras.optimizers.SGD(learning_rate=learning_rate)'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.]
Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py", line 30, in <module>
    pipeline.main()
  File "src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py", line 21, in main
    base_model.update_base_model()
  File "c:\users\chirag sharma\desktop\gitdemo\kidney-disease-classification\src\Kidney_Disease_Classification\components\prepare_base_model.py", line 53, in update_base_model
    self.full_model = self._prepare_full_model(
  File "c:\users\chirag sharma\desktop\gitdemo\kidney-disease-classification\src\Kidney_Disease_Classification\components\prepare_base_model.py", line 43, in _prepare_full_model
    full_model.compile(
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\saving\legacy\serialization.py", line 368, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown optimizer: 'tf.keras.optimizers.SGD(learning_rate=learning_rate)'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
[2025-07-01 19:54:51,610: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:54:51,634: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 19:54:51,643: INFO: common: created directory at: artifacts]
[2025-07-01 19:54:51,643: INFO: common: created directory at: artifacts]
[2025-07-01 19:54:53,136: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 19:56:07,937: INFO: stage_02_prepare_base_model: *******************]
[2025-07-01 19:56:07,937: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-07-01 19:56:07,946: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:56:07,946: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 19:56:07,946: INFO: common: created directory at: artifacts]
[2025-07-01 19:56:07,946: INFO: common: created directory at: artifacts]
[2025-07-01 19:56:08,599: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 19:56:08,864: ERROR: stage_02_prepare_base_model: Unknown optimizer: 'tf.keras.optimizers.SGD(learning_rate=learning_rate)'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.]
Traceback (most recent call last):
  File "src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py", line 30, in <module>
    pipeline.main()
  File "src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py", line 21, in main
    base_model.update_base_model()
  File "c:\users\chirag sharma\desktop\gitdemo\kidney-disease-classification\src\Kidney_Disease_Classification\components\prepare_base_model.py", line 53, in update_base_model
    self.full_model = self._prepare_full_model(
  File "c:\users\chirag sharma\desktop\gitdemo\kidney-disease-classification\src\Kidney_Disease_Classification\components\prepare_base_model.py", line 43, in _prepare_full_model
    full_model.compile(
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Chirag Sharma\anaconda3\envs\Kidney\lib\site-packages\keras\saving\legacy\serialization.py", line 368, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown optimizer: 'tf.keras.optimizers.SGD(learning_rate=learning_rate)'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
[2025-07-01 19:59:06,524: INFO: stage_02_prepare_base_model: *******************]
[2025-07-01 19:59:06,524: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2025-07-01 19:59:06,532: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:59:06,532: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 19:59:06,532: INFO: common: created directory at: artifacts]
[2025-07-01 19:59:06,532: INFO: common: created directory at: artifacts]
[2025-07-01 19:59:07,274: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-01 19:59:07,620: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2025-07-01 19:59:24,047: INFO: stage_03_model_training: *******************]
[2025-07-01 19:59:24,047: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-07-01 19:59:24,047: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:59:24,056: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 19:59:24,056: INFO: common: created directory at: artifacts]
[2025-07-01 19:59:24,056: INFO: common: created directory at: artifacts\training]
[2025-07-01 22:51:32,815: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-01 22:51:56,327: INFO: stage_04_model_evaluation: *******************]
[2025-07-01 22:51:56,328: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-01 22:51:56,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 22:51:56,337: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 22:51:56,338: INFO: common: created directory at: artifacts]
[2025-07-01 22:58:17,302: INFO: common: json file saved at: scores.json]
[2025-07-01 22:58:17,306: INFO: common: json file saved at: scores.json]
[2025-07-01 22:58:17,308: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-07-01 22:59:14,741: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.69.98.185:8080]
[2025-07-01 22:59:14,742: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-07-01 22:59:14,745: INFO: _internal:  * Restarting with stat]
[2025-07-01 22:59:21,154: WARNING: _internal:  * Debugger is active!]
[2025-07-01 22:59:21,170: INFO: _internal:  * Debugger PIN: 250-466-829]
[2025-07-01 22:59:39,126: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 22:59:39] "GET / HTTP/1.1" 200 -]
[2025-07-01 23:00:04,761: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 23:00:04] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 23:00:30,413: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 23:00:30] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 23:00:46,991: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 23:00:46] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 23:01:03,528: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 23:01:03] "POST /predict HTTP/1.1" 200 -]
[2025-07-01 23:01:23,655: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000150567794C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-07-01 23:01:23,659: INFO: _internal: 127.0.0.1 - - [01/Jul/2025 23:01:23] "POST /predict HTTP/1.1" 200 -]
